FROM python:3.12-slim

WORKDIR /app

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Expose port
EXPOSE 8000

# Run uv sync at startup (since /app is mounted as volume) and then start uvicorn
CMD ["sh", "-c", "uv sync && uv run uvicorn testproject.main:app --host 0.0.0.0 --port 8000 --reload"]
